# Generated by Django 3.2.2 on 2021-08-02 07:42

import BackPyPortfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=BackPyPortfolio.models.upload_image_path)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
