# Generated by Django 3.2.5 on 2021-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyTeam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
