# Generated by Django 3.2.5 on 2021-07-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyTeam', '0002_teammembers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='personal_cv',
            field=models.CharField(default='test', max_length=150),
        ),
    ]
