# Generated by Django 3.2.5 on 2021-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyTeam', '0003_teammembers_personal_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='personal_cv',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
