# Generated by Django 3.2.2 on 2021-07-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UIUX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[], max_length=50)),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
