# Generated by Django 3.2.2 on 2021-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('UI', 'UI'), ('UX', 'UX')], max_length=50)),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UIUX',
        ),
    ]
