# Generated by Django 3.2.2 on 2021-07-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0005_alter_designs_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designs',
            new_name='interface',
        ),
    ]
