# Generated by Django 3.2.2 on 2021-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0006_rename_designs_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('UI', 'UI Designers'), ('UX', 'UX Designers')], max_length=50)),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='interface',
        ),
    ]
