# Generated by Django 3.2.2 on 2021-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0007_auto_20210724_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designers',
            name='title',
            field=models.CharField(choices=[('UI', 'UI Designers'), ('UX', 'UX Designers')], default='UI', max_length=50),
        ),
    ]
