# Generated by Django 3.2.2 on 2021-07-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0008_alter_designers_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designers',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
