# Generated by Django 3.2.2 on 2021-07-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0009_alter_designers_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designers',
            name='title',
            field=models.CharField(choices=[('UI', 'UI Designers'), ('UX', 'UX Designers')], default='UI', max_length=50),
        ),
    ]
