# Generated by Django 3.2.2 on 2021-07-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0010_alter_designers_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designers',
            new_name='Designer',
        ),
    ]
