# Generated by Django 3.2.2 on 2021-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPyService', '0012_auto_20210724_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icons',
            field=models.CharField(choices=[('wand', 'Clean Code (magic wand)'), ('comments-smiley', 'DEDICATED SUPPORT (smile comment)'), ('heart', 'USER FRIENDLY (heart)'), ('palette', 'MODERN DESIGN'), ('headphone-alt', 'FAST SUPPORT (headphone)'), ('light-bulb', 'EXCELLENT IDEAS (bulb lamp)')], default='ti-wand', max_length=30),
        ),
    ]
