# Generated by Django 3.2.2 on 2021-07-22 07:25

import BackPySlider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BeforeText', models.CharField(max_length=20)),
                ('MiddleText', models.CharField(help_text='this is alternative text between two words', max_length=5)),
                ('AfterText', models.CharField(max_length=20)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('GoButton', models.CharField(max_length=10)),
                ('SliderImage', models.ImageField(blank=True, null=True, upload_to=BackPySlider.models.upload_image_path)),
            ],
        ),
    ]
