# Generated by Django 3.2.5 on 2021-07-27 08:29

import BackPyBlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date_created', models.TimeField(auto_now=True)),
                ('blog_content', models.TextField()),
                ('write', models.CharField(max_length=150)),
                ('visit_count', models.IntegerField()),
                ('share', models.CharField(max_length=500)),
                ('link_content', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Image size: 360 × 240', null=True, upload_to=BackPyBlog.models.upload_image_path)),
            ],
        ),
    ]
