# Generated by Django 3.2.5 on 2021-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
