# Generated by Django 3.2.5 on 2021-07-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0002_sme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMe',
        ),
    ]
