# Generated by Django 3.2.5 on 2021-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0003_delete_sme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='tooltip',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='tooltipshow',
            field=models.CharField(default='tooltip', max_length=50),
        ),
    ]
