# Generated by Django 3.2.5 on 2021-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0004_auto_20210722_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='tooltipshow',
            field=models.CharField(max_length=50),
        ),
    ]
