# Generated by Django 3.2.5 on 2021-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0005_alter_socialmedia_tooltipshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(choices=[('telegram', 'telegram'), ('instagram', 'instagram'), ('github', 'github'), ('linkedin', 'linkedin'), ('facebook', 'facebook'), ('whatsapp', 'whatsapp'), ('twitter', 'twitter'), ('youtube', 'youtube'), ('pinterest', 'pinterest'), ('skype', 'skype'), ('dribbble', 'dribbble'), ('reddit', 'reddit'), ('stack-overflow', 'stack-overflow')], max_length=50),
        ),
    ]
