# Generated by Django 3.2.5 on 2021-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0006_alter_socialmedia_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('telegram', 'telegram'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp'), ('twitter', 'twitter'), ('pinterest', 'pinterest'), ('skype', 'skype'), ('reddit', 'reddit')], max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
