# Generated by Django 3.2.5 on 2021-07-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0007_shareus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('ti-layers-alt', 'ti-layers-alt'), ('ti-map-alt', 'ti-map-alt'), ('fa fa-coffee', 'fa fa-coffee'), ('ti-face-smile', 'ti-face-smile'), ('ti-gallery', 'ti-gallery'), ('ti-agenda', 'ti-agenda'), ('ti-server', 'ti-server'), ('ti-stats-up', 'ti-stats-up'), ('ti-world', 'ti-world'), ('ti-bolt', 'ti-bolt'), ('ti-check', 'ti-check'), ('ti-check-box', 'ti-check-box'), ('ti-announcement', 'ti-announcement'), ('ti-eye', 'ti-eye'), ('ti-heart', 'ti-heart'), ('ti-pencil', 'ti-pencil'), ('ti-bookmark', 'ti-bookmark'), ('ti-desktop', 'ti-desktop')], max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
