# Generated by Django 3.2.5 on 2021-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPySetting', '0008_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
